apiVersion: v1
kind: Service
metadata:
  name: {{ include "inx-eventhorizon-tool-legacymigration.fullname" . }}
  labels:
    {{- include "inx-eventhorizon-tool-legacymigration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inx-eventhorizon-tool-legacymigration.selectorLabels" . | nindent 4 }}
