{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inx-eventhorizon-tool-legacymigration.serviceAccountName" . }}
  labels:
    {{- include "inx-eventhorizon-tool-legacymigration.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
